// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB2PR3zyJAGgtt2GhKQ8de7O52Z-gx4Tk',
    appId: '1:766465796018:android:afab5b2f6b13077d21e6ab',
    messagingSenderId: '766465796018',
    projectId: 'payday-9d1d7',
    storageBucket: 'payday-9d1d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RTbGdxuj31KeWvnnZXHp9N0Nr3mUkjU',
    appId: '1:766465796018:ios:b7be65ff263f302c21e6ab',
    messagingSenderId: '766465796018',
    projectId: 'payday-9d1d7',
    storageBucket: 'payday-9d1d7.firebasestorage.app',
    androidClientId: '766465796018-3tjjp00o8sfve79h2rmta1i2lp7putah.apps.googleusercontent.com',
    iosClientId: '766465796018-uso1fsvjdia6gg25td1hi4ai0ihe8mhc.apps.googleusercontent.com',
    iosBundleId: 'com.codenzi.payday',
  );

}